export const part2Static = {
    partNumber: 2,
    type: "Listening",
    questions: [
        {
            id: "d96ea8fb-21c0-474f-8013-90cbb2a06513",
            part: 2,
            type: "Listening",
            question:
                "Perferendis confero amicitia amiculum tersus tantum altus utpote cursim impedit contabesco aestus comminor vapulus valeo.",
            options: ["packaging", "hutch", "appliance", "derby"],
            answer: "packaging",
            audioURL: "https://concerned-soup.net/audio_Lc7LnLj0.mp3",
        },
        {
            id: "70d9e132-b530-4a40-8826-59968cf8d2f4",
            part: 2,
            type: "Listening",
            question:
                "Commodi saepe thema adduco vitae caute demulceo crudelis vorago thymbra nostrum trucido sophismata ullam absconditus.",
            options: ["pendant", "sunbeam", "convection", "goodwill"],
            answer: "convection",
            audioURL: "https://acclaimed-championship.name/audio_4ozHpUSc.mp3",
        },
        {
            id: "f341af4e-4a9c-4d77-86a7-0f4174ee89dc",
            part: 2,
            type: "Listening",
            question:
                "Textus solvo crebro aestas denique avaritia cohors illo sordeo harum compono.",
            options: ["chow", "coordination", "hydrocarbon", "edge"],
            answer: "hydrocarbon",
            audioURL: "https://lighthearted-case.org/audio_1sGaneNi.mp3",
        },
        {
            id: "23df42c5-8c53-4929-a735-84c54dd4db15",
            part: 2,
            type: "Listening",
            question:
                "Tametsi delicate amita creator tantum administratio theologus paulatim absconditus concido decet deleo demoror calculus ducimus.",
            options: ["vista", "innovation", "shadowbox", "in-joke"],
            answer: "shadowbox",
            audioURL: "https://important-archaeology.com/audio_Jk25aizS.mp3",
        },
        {
            id: "d76dd861-9a4b-4130-89bd-036a4e661e31",
            part: 2,
            type: "Listening",
            question:
                "Infit venio hic tepesco careo vestrum vero alias delibero volaticus arcus stips repudiandae vitium.",
            options: ["fog", "permafrost", "strategy", "exterior"],
            answer: "fog",
            audioURL: "https://courageous-decryption.biz/audio_8ev3Z5fC.mp3",
        },
        {
            id: "d5687af1-7996-41e8-8ac8-8ba42415617b",
            part: 2,
            type: "Listening",
            question: "Cogito umquam addo patrocinor ducimus.",
            options: ["agreement", "cleaner", "bracelet", "awareness"],
            answer: "agreement",
        },
        {
            id: "fb825c4a-ea90-43b2-bef7-c5cdad75ab48",
            part: 2,
            type: "Listening",
            question:
                "Vulgivagus suppono tero paens decet celebrer suscipio corrumpo.",
            options: [
                "switchboard",
                "deployment",
                "accelerator",
                "coordination",
            ],
            answer: "deployment",
            audioURL: "https://critical-designation.com/audio_vjM9VOll.mp3",
        },
        {
            id: "c684ccd5-3f0d-48c5-b36f-ac80cd43a393",
            part: 2,
            type: "Listening",
            question:
                "Tyrannus aestus volva amplus aro thermae circumvenio complectus arcesso aro cinis commodo.",
            options: ["conservation", "impostor", "bowler", "receptor"],
            answer: "conservation",
            audioURL: "https://shady-tuxedo.org/audio_hpjZuIYT.mp3",
        },
        {
            id: "862729b4-c5c7-4998-94ef-f1283724e538",
            part: 2,
            type: "Listening",
            question:
                "Ara carmen ustilo decens derelinquo vindico tribuo compello verecundia depereo venustas cras verbera.",
            options: ["pliers", "creature", "airman", "antelope"],
            answer: "antelope",
            audioURL: "https://striking-middle.com/audio_GjrYwLXJ.mp3",
        },
        {
            id: "baf04200-46ba-4a33-9b6b-224ba7c028db",
            part: 2,
            type: "Listening",
            question:
                "Cerno tersus urbanus ambitus curiositas umbra deprimo comparo.",
            options: ["nightlife", "peninsula", "repeat", "godparent"],
            answer: "godparent",
        },
        {
            id: "0f97f476-f217-4bff-9940-254a3fc6f7c8",
            part: 2,
            type: "Listening",
            question:
                "Acer aegre demo vestrum verecundia alius patrocinor vero cotidie viscus.",
            options: ["edge", "bathrobe", "stitcher", "deduction"],
            answer: "edge",
            audioURL: "https://fake-opera.name/audio_EOa8426z.mp3",
        },
        {
            id: "d279169c-f46a-42dc-9e55-2b9392630b2a",
            part: 2,
            type: "Listening",
            question:
                "Consequuntur quis tyrannus ambitus volaticus universe sto vereor credo trepide.",
            options: ["breastplate", "halt", "entry", "formamide"],
            answer: "formamide",
            audioURL: "https://ordinary-secrecy.net/audio_Jj8x8czh.mp3",
        },
        {
            id: "326bd928-ba5d-4060-b189-098d3068de71",
            part: 2,
            type: "Listening",
            question:
                "Saepe quibusdam illo strenuus custodia deleo cimentarius volaticus spes acceptus aggero valetudo absorbeo debeo somnus.",
            options: ["detective", "section", "prohibition", "electronics"],
            answer: "prohibition",
            audioURL: "https://slimy-hubris.name/audio_BNw7IW2u.mp3",
        },
        {
            id: "96580cc3-c786-4f6e-abfa-9295734c61de",
            part: 2,
            type: "Listening",
            question:
                "Suasoria canto utroque dedecor volup vulpes terreo voluptates vitiosus.",
            options: ["drive", "clamp", "tuber", "sauerkraut"],
            answer: "drive",
            audioURL: "https://fixed-baseboard.biz/audio_q5Dy8sfD.mp3",
        },
        {
            id: "506fa763-df6e-4de7-8897-f2b8a7b3d87a",
            part: 2,
            type: "Listening",
            question:
                "Cubicularis tres deputo adipiscor caelestis damnatio commemoro delicate.",
            options: ["punctuation", "airbus", "yeast", "footrest"],
            answer: "airbus",
            audioURL: "https://yearly-recovery.biz/audio_D7QUQcQD.mp3",
        },
        {
            id: "174474f0-90e3-4445-affb-8319b5dcee55",
            part: 2,
            type: "Listening",
            question: "Decor subiungo aptus non desidero.",
            options: ["grandpa", "fencing", "halt", "fun"],
            answer: "grandpa",
            audioURL: "https://tidy-ceramics.com/audio_8Fc2kQfV.mp3",
        },
        {
            id: "33a5e668-82db-4c72-9f90-f4f3be5ebcb0",
            part: 2,
            type: "Listening",
            question:
                "Atavus degusto veritatis studio alius brevis copiose suscipio.",
            options: ["dusk", "amnesty", "pasta", "thorn"],
            answer: "pasta",
            audioURL: "https://rubbery-sauerkraut.info/audio_Oy1emVGf.mp3",
        },
        {
            id: "25ac0c39-e9a8-4073-81d2-23e93f80f6b4",
            part: 2,
            type: "Listening",
            question:
                "Crustulum viscus conatus caput admoneo depono amitto decens conscendo.",
            options: ["offset", "backbone", "department", "switch"],
            answer: "offset",
            audioURL: "https://glass-ethyl.com/audio_DU2N9ePB.mp3",
        },
        {
            id: "e115b76c-8987-4e4c-9f7a-b5a0a93126e1",
            part: 2,
            type: "Listening",
            question: "Harum utrum cur amor expedita.",
            options: ["veto", "slipper", "settler", "wilderness"],
            answer: "settler",
        },
        {
            id: "9a89dfe7-9325-4fff-a8ac-9ffa6ed44fc3",
            part: 2,
            type: "Listening",
            question: "Viriliter cogo corona timidus vere.",
            options: ["fit", "responsibility", "language", "adaptation"],
            answer: "responsibility",
            audioURL: "https://trained-clavicle.org/audio_RD3W8DgK.mp3",
        },
        {
            id: "836da667-eef2-48dc-9665-096ca47eb56c",
            part: 2,
            type: "Listening",
            question: "Tabesco nam denuo accusantium vinitor.",
            options: ["chiffonier", "mixture", "nucleotidase", "almighty"],
            answer: "nucleotidase",
        },
        {
            id: "23e52d7c-6d50-4d74-91fc-25c8eabfeb02",
            part: 2,
            type: "Listening",
            question:
                "Causa aetas strenuus tamen cibus crepusculum consectetur adinventitias aestivus decerno benigne voluntarius delibero via.",
            options: ["charm", "exploration", "flight", "vol"],
            answer: "flight",
            audioURL: "https://heartfelt-lyre.info/audio_E8a1XtIk.mp3",
        },
        {
            id: "925832bc-8f8e-400b-8765-c1fb2395fd73",
            part: 2,
            type: "Listening",
            question: "Utor cohaero attero curriculum cilicium.",
            options: ["gradient", "defendant", "sediment", "scout"],
            answer: "defendant",
            audioURL: "https://calculating-creature.com/audio_VN5imzVD.mp3",
        },
        {
            id: "e54ea308-7bca-4fa6-b577-948a5a6695b0",
            part: 2,
            type: "Listening",
            question:
                "Corporis patria voluptates peior deputo sublime vilis cuius.",
            options: ["gray", "chow", "maintainer", "fen"],
            answer: "chow",
            audioURL: "https://soulful-morbidity.net/audio_hPquZWC7.mp3",
        },
        {
            id: "08d19259-50f0-496d-8652-72c2bdcbd454",
            part: 2,
            type: "Listening",
            question:
                "Cunctatio pauci sonitus solium absens clibanus arto suspendo cur teneo.",
            options: ["outrun", "printer", "premeditation", "corporation"],
            answer: "premeditation",
            audioURL: "https://rosy-unblinking.name/audio_X2VwTLHS.mp3",
        },
    ],
};
