export const part4Static = {
    partNumber: 4,
    type: "Listening",
    questions: [
        {
            id: "91e6ef39-ff50-4e0c-a501-1cab1807abfb",
            part: 4,
            type: "Listening",
            question:
                "Suadeo crux termes suadeo usitas viscus subnecto dicta culpo caelum deserunt soluta acsi dolores neque.",
            options: ["lashes", "moment", "behest", "lamp"],
            answer: "lashes",
            audioURL: "https://impeccable-steeple.name/audio_3wtqUXuI.mp3",
        },
        {
            id: "0736d8ae-551b-4ec5-89fc-c8ee745828c1",
            part: 4,
            type: "Listening",
            question: "Vita suasoria admiratio in aeternus terror sollers.",
            options: ["sonata", "shadowbox", "jellyfish", "thorn"],
            answer: "sonata",
            audioURL: "https://next-riser.net/audio_xUMHvUow.mp3",
        },
        {
            id: "364355bd-679e-4712-b4bf-078e529f791d",
            part: 4,
            type: "Listening",
            question: "Exercitationem adflicto dedecor denego ambitus.",
            options: ["casket", "summer", "relative", "bog"],
            answer: "casket",
            audioURL: "https://sorrowful-apparatus.org/audio_aW5KkfFh.mp3",
        },
        {
            id: "c9915d47-a5fb-4df4-b29f-8b1af5875dcf",
            part: 4,
            type: "Listening",
            question:
                "Ater acidus truculenter coniecto crebro confugo beatae clarus advoco umerus repellendus magnam hic distinctio pecus.",
            options: ["pliers", "understanding", "bell", "reporter"],
            answer: "understanding",
            audioURL: "https://tame-interviewer.name/audio_2v18Qfxe.mp3",
        },
        {
            id: "930c9eb5-34ee-47bd-b65f-c7f08c41fd9e",
            part: 4,
            type: "Listening",
            question: "Curis audax tepesco vereor sit.",
            options: ["carboxyl", "best-seller", "alb", "representation"],
            answer: "representation",
            audioURL: "https://sardonic-self-confidence.com/audio_EukqYqpX.mp3",
        },
        {
            id: "72000736-6118-4ce7-a50a-cdd1c436f1fe",
            part: 4,
            type: "Listening",
            question:
                "Dolore alo arbor bene carpo ab celebrer solitudo solum earum atavus desino.",
            options: ["label", "mom", "drug", "finer"],
            answer: "label",
            audioURL: "https://limited-density.org/audio_w9NrqQQJ.mp3",
        },
        {
            id: "000e5b77-5a42-49dc-9d1a-7d3fe779c29b",
            part: 4,
            type: "Listening",
            question: "Valens laudantium allatus numquam optio.",
            options: ["coil", "suitcase", "poppy", "derby"],
            answer: "coil",
            audioURL: "https://well-groomed-switch.org/audio_Sj6Qa0xW.mp3",
        },
        {
            id: "e6380fec-5c68-4643-b077-08d3796ddf1c",
            part: 4,
            type: "Listening",
            question:
                "Pauper pauci tamdiu decerno dedecor sub velociter armarium ago tego.",
            options: ["expense", "glider", "trick", "elevation"],
            answer: "trick",
            audioURL: "https://plump-reach.name/audio_CfET1Cgr.mp3",
        },
        {
            id: "9c97cd33-abcd-49ab-af07-ed0e4db8e63b",
            part: 4,
            type: "Listening",
            question:
                "Vomica derideo ater tamquam corporis coruscus utique terga cotidie clibanus vespillo adinventitias.",
            options: ["boyfriend", "submitter", "yarmulke", "mixture"],
            answer: "boyfriend",
            audioURL: "https://powerful-pliers.org/audio_NaD33HRt.mp3",
        },
        {
            id: "9df9cb22-bba5-4049-a04d-0cbd9fdfd215",
            part: 4,
            type: "Listening",
            question:
                "Absque turpis alo doloremque vestrum vomito somnus vado abduco xiphias usque itaque.",
            options: ["sock", "toothpick", "plastic", "postbox"],
            answer: "toothpick",
            audioURL: "https://remorseful-statue.info/audio_ngyuZZCi.mp3",
        },
        {
            id: "d3cd9d05-4c60-4c4f-aa30-39d02d94c6d0",
            part: 4,
            type: "Listening",
            question:
                "Tredecim cur cribro alveus vicinus causa officiis voveo angulus vesper vinum cohibeo uterque tabesco cotidie.",
            options: ["deed", "best-seller", "declaration", "allocation"],
            answer: "best-seller",
            audioURL: "https://potable-noon.com/audio_cpNVInhz.mp3",
        },
        {
            id: "1aefd6f9-0608-4b32-9aea-f4a187d307ac",
            part: 4,
            type: "Listening",
            question:
                "Aqua suadeo voluntarius neque est colo vulnus sub adimpleo odit.",
            options: ["fraudster", "edge", "meander", "diagram"],
            answer: "edge",
            audioURL: "https://incomparable-retention.org/audio_nbWXuehC.mp3",
        },
        {
            id: "586f0397-fe43-42b1-87fc-b24a2f60832d",
            part: 4,
            type: "Listening",
            question:
                "Debilito cultura arca doloribus arca verbum aeneus pecto comes natus una valeo turba.",
            options: ["disconnection", "accountability", "lift", "bug"],
            answer: "bug",
            audioURL: "https://unkempt-guard.com/audio_Eec6ksS3.mp3",
        },
        {
            id: "e64d5669-c2c9-48ca-8b71-56e4da188ff4",
            part: 4,
            type: "Listening",
            question: "Complectus subito atque capio copia tener arx.",
            options: ["bandwidth", "space", "jacket", "disk"],
            answer: "bandwidth",
            audioURL: "https://pointless-dwell.name/audio_qRqKYSVJ.mp3",
        },
        {
            id: "628b071e-d6f1-4e53-972d-ff25c00d719f",
            part: 4,
            type: "Listening",
            question:
                "Pax praesentium argentum umquam suus spoliatio sufficio pax ait.",
            options: ["bookend", "heating", "warming", "patroller"],
            answer: "heating",
            audioURL: "https://pleased-parsnip.biz/audio_PCrQTF50.mp3",
        },
        {
            id: "d47f06cc-a78b-4d1a-9b05-6db183a6a9d4",
            part: 4,
            type: "Listening",
            question:
                "Incidunt cupiditas crepusculum volubilis ullus theatrum spectaculum adsum armarium centum verecundia magni causa auxilium accusantium.",
            options: ["ecliptic", "sand", "hope", "declaration"],
            answer: "hope",
            audioURL: "https://colorful-fencing.net/audio_r8UyDeO9.mp3",
        },
        {
            id: "a44a0fcf-72ae-4c7c-8ab2-e6ec28fe2096",
            part: 4,
            type: "Listening",
            question:
                "Sublime curriculum cornu comitatus uxor totus tamisium volup.",
            options: ["cycle", "management", "contractor", "concentration"],
            answer: "contractor",
            audioURL: "https://impractical-nectarine.org/audio_kxUMF5gZ.mp3",
        },
        {
            id: "446846b2-3552-4895-8cae-0c07da1e780f",
            part: 4,
            type: "Listening",
            question:
                "Aegrus tyrannus vis capillus commodi sponte tremo cinis aspicio depono aetas nihil ratione.",
            options: ["heating", "fishery", "interviewer", "platter"],
            answer: "platter",
            audioURL: "https://velvety-pick.name/audio_NA9I2eBF.mp3",
        },
        {
            id: "ccbffc75-7900-47da-8dee-0d3e5c12b994",
            part: 4,
            type: "Listening",
            question:
                "Advenio defendo custodia temporibus ventosus temptatio addo amaritudo vulgus accusantium.",
            options: ["peninsula", "puritan", "appliance", "lieu"],
            answer: "lieu",
            audioURL: "https://short-vestment.org/audio_0mELTygq.mp3",
        },
        {
            id: "c7f7aefc-af96-44f0-8858-b50fff583c9c",
            part: 4,
            type: "Listening",
            question:
                "Pauper voluntarius compello cena stillicidium comes solus vesica victus vaco ciminatio comitatus calcar.",
            options: ["boyfriend", "confusion", "scenario", "octave"],
            answer: "confusion",
            audioURL: "https://big-swing.biz/audio_EC6wvg1h.mp3",
        },
        {
            id: "44110c62-72a3-464f-8ec3-86c79055c3ab",
            part: 4,
            type: "Listening",
            question:
                "Calcar tepidus acerbitas aggero campana usus creo tantum dolorum caelum sublime valeo cursus uterque atqui.",
            options: ["sand", "developmental", "subexpression", "dash"],
            answer: "subexpression",
            audioURL: "https://clear-cut-convection.org/audio_t0hxtFXC.mp3",
        },
        {
            id: "19a88e43-2a8e-43c6-8bc7-43b150d90d52",
            part: 4,
            type: "Listening",
            question:
                "Alienus contabesco crudelis aegrus deripio adeptio creptio decretum tenetur vulticulus aestus adsuesco.",
            options: ["jury", "affiliate", "barracks", "freezing"],
            answer: "barracks",
            audioURL: "https://enchanted-account.info/audio_XkGlGL82.mp3",
        },
        {
            id: "cb8e7167-053c-49e3-a3fc-c249bf6118de",
            part: 4,
            type: "Listening",
            question:
                "Ante ad trans officiis demitto calamitas creator conculco accommodo sumptus.",
            options: ["crest", "privilege", "exhaust", "word"],
            answer: "word",
            audioURL: "https://better-thread.com/audio_VKoxOTnt.mp3",
        },
        {
            id: "ad8ebf8b-3552-4850-a81d-2022ac2797f4",
            part: 4,
            type: "Listening",
            question:
                "Uterque cenaculum acervus pauci defessus maiores adnuo veniam pectus delicate eveniet volva.",
            options: ["sideboard", "birdbath", "halt", "word"],
            answer: "word",
            audioURL: "https://growing-skyscraper.net/audio_YMUJMz9v.mp3",
        },
        {
            id: "6dfb5ae4-41a6-43e0-8849-c5a6666993de",
            part: 4,
            type: "Listening",
            question: "Varietas vigilo carmen crinis tersus.",
            options: ["leading", "godparent", "markup", "certification"],
            answer: "markup",
            audioURL: "https://judicious-trench.org/audio_Q96Viah8.mp3",
        },
        {
            id: "aa89a30a-4bb6-4d05-a6c6-2d5a8aff6856",
            part: 4,
            type: "Listening",
            question:
                "Confero amet autem corrumpo derideo canis civis bardus cogo tumultus acquiro vulariter appono deserunt sortitus.",
            options: [
                "cross-contamination",
                "tomatillo",
                "quinoa",
                "valentine",
            ],
            answer: "valentine",
            audioURL: "https://hoarse-schedule.org/audio_RkEgeqqI.mp3",
        },
        {
            id: "06ff6d06-75a3-4fe9-8720-87163c3c2d6a",
            part: 4,
            type: "Listening",
            question: "Cunctatio testimonium necessitatibus theatrum vestrum.",
            options: ["colonialism", "birdbath", "galoshes", "bowling"],
            answer: "bowling",
            audioURL: "https://dental-retrospectivity.info/audio_4PUTKWaq.mp3",
        },
        {
            id: "0147fc08-02a8-43fd-9534-ce389f88c2c4",
            part: 4,
            type: "Listening",
            question:
                "Tego strenuus dens vapulus absorbeo coniecto angustus delicate claro modi suus arguo tamdiu vix.",
            options: ["carnival", "avalanche", "trash", "adaptation"],
            answer: "carnival",
            audioURL: "https://rare-giant.net/audio_RmWNI7mu.mp3",
        },
        {
            id: "c814f38f-6958-4c6d-8d77-a9db28796384",
            part: 4,
            type: "Listening",
            question:
                "Repellat admitto arguo tumultus voluptatibus harum cotidie impedit et tracto aperte viduo versus adnuo carcer.",
            options: ["substitution", "cash", "marathon", "elevation"],
            answer: "cash",
            audioURL: "https://dependent-solution.net/audio_XOLkx9wH.mp3",
        },
        {
            id: "3447fbc3-e302-40fc-ac91-eca97c88b22a",
            part: 4,
            type: "Listening",
            question:
                "Degusto clarus illum sollers velociter concedo victoria usque desolo.",
            options: ["decongestant", "tuxedo", "integer", "gift"],
            answer: "gift",
            audioURL: "https://drab-flood.biz/audio_uLEKrSSL.mp3",
        },
    ],
};
