export const part3Static = {
    partNumber: 3,
    type: "Listening",
    questions: [
        {
            id: "cdae031c-35b7-4ac7-a735-79db7768c135",
            part: 3,
            type: "Listening",
            question: "Aeger succedo aurum avaritia cresco creptio.",
            options: ["divine", "eyebrow", "jet", "folklore"],
            answer: "jet",
            audioURL: "https://silky-passport.org/audio_3aDQJmTK.mp3",
        },
        {
            id: "93868648-5d44-475b-9795-33f878e6cebe",
            part: 3,
            type: "Listening",
            question:
                "Calculus vinitor vindico ago inflammatio collum clibanus adsuesco asporto arcesso.",
            options: ["dredger", "tectonics", "vol", "leading"],
            answer: "tectonics",
        },
        {
            id: "85b0ad0b-86e1-4a7a-a364-8948e7d5d28b",
            part: 3,
            type: "Listening",
            question: "Utor damno talio cibo volubilis pel auctus.",
            options: ["birth", "interior", "gift", "armchair"],
            answer: "birth",
            audioURL: "https://immaculate-mom.biz/audio_3byUizIw.mp3",
        },
        {
            id: "b487e35c-02d5-49cd-a24d-8173fe8ce17c",
            part: 3,
            type: "Listening",
            question:
                "Aveho solus totam pecus corroboro pecus suscipit amplitudo defleo triumphus centum capillus.",
            options: ["travel", "repeat", "approach", "cassava"],
            answer: "repeat",
            audioURL: "https://confused-antelope.name/audio_iDd0gvkA.mp3",
        },
        {
            id: "4edc8804-7a10-4dbc-b3a6-33a3fb41bccd",
            part: 3,
            type: "Listening",
            question:
                "Aspicio dolorem voluptas tabula articulus bestia taceo vomer demulceo victus incidunt alveus trado.",
            options: ["napkin", "newsletter", "swath", "lotion"],
            answer: "newsletter",
            audioURL: "https://stark-mortise.net/audio_xmuO1Ppk.mp3",
        },
        {
            id: "37a3f30e-4d8c-48a8-b411-54b45c408c4b",
            part: 3,
            type: "Listening",
            question:
                "Barba bene absconditus universe audax abstergo adulescens consequatur quaerat.",
            options: ["calculus", "thread", "mouser", "developing"],
            answer: "mouser",
            audioURL: "https://unrealistic-metal.info/audio_CjY61KQM.mp3",
        },
        {
            id: "4be20150-aaad-488c-8abd-e601d13dfe8b",
            part: 3,
            type: "Listening",
            question:
                "Repellendus vado vinum viridis degenero armarium venio sit apto arbitro taedium utpote cohaero.",
            options: ["deed", "optimal", "marketplace", "responsibility"],
            answer: "marketplace",
            audioURL: "https://aggravating-icebreaker.info/audio_RhdmqNfV.mp3",
        },
        {
            id: "b2e37fa2-f88b-4cd3-8e81-05feb16f8fae",
            part: 3,
            type: "Listening",
            question: "Quos quae aptus bene curis.",
            options: ["roundabout", "hyena", "fat", "configuration"],
            answer: "roundabout",
            audioURL: "https://deafening-fort.com/audio_UpIo0pMR.mp3",
        },
        {
            id: "997e76f5-42d1-450f-bd30-4d4bda9b801a",
            part: 3,
            type: "Listening",
            question: "Modi curo illo tergo video cado.",
            options: ["merit", "brush", "embarrassment", "mantua"],
            answer: "brush",
            audioURL: "https://dismal-dredger.com/audio_x3mnGYu7.mp3",
        },
        {
            id: "759bc15c-ed2b-4fe6-84fc-aaf1b6366bc3",
            part: 3,
            type: "Listening",
            question:
                "Asper iure combibo confero curriculum angustus contigo cohaero tergo tactus talio cogo infit conduco.",
            options: ["publicity", "thigh", "adrenalin", "object"],
            answer: "adrenalin",
            audioURL: "https://known-cheetah.biz/audio_HZ0JMc4H.mp3",
        },
        {
            id: "7eba6f3b-4b6e-4880-8522-ad69f370affc",
            part: 3,
            type: "Listening",
            question:
                "Comprehendo creta bene desidero contego bardus coadunatio aliquid eligendi angustus acceptus alveus.",
            options: ["minor", "majority", "pecan", "operating"],
            answer: "operating",
            audioURL: "https://delirious-publication.name/audio_Dg1s8zof.mp3",
        },
        {
            id: "579fca55-9583-4183-9c2c-af3e276ab16e",
            part: 3,
            type: "Listening",
            question:
                "Acidus teneo astrum crudelis tumultus tristis deripio temporibus adaugeo.",
            options: ["cardboard", "resource", "blowgun", "orchid"],
            answer: "orchid",
            audioURL: "https://questionable-pop.org/audio_5mb8dpEv.mp3",
        },
        {
            id: "0c68c5a5-4852-433e-8dcc-e7361f1ed59d",
            part: 3,
            type: "Listening",
            question: "Error numquam capto crebro vae patria deporto.",
            options: ["slide", "gastropod", "napkin", "pomelo"],
            answer: "gastropod",
            audioURL: "https://cautious-steak.info/audio_i8lOcMeX.mp3",
        },
        {
            id: "79726cc0-add3-4470-b127-eb2ea34d99d4",
            part: 3,
            type: "Listening",
            question:
                "Curto totidem aeger alter vigilo currus alii voluptates accendo mollitia coma una certus speciosus.",
            options: ["sustenance", "abacus", "dulcimer", "flu"],
            answer: "sustenance",
            audioURL: "https://sudden-bowling.name/audio_XHcl9dt7.mp3",
        },
        {
            id: "1a0e513a-1e43-4dc6-81d4-0844d1aad18e",
            part: 3,
            type: "Listening",
            question:
                "Viduo vado umerus apostolus cui vivo officia tergeo utrum ait deludo aestus amor.",
            options: ["availability", "range", "yeast", "jury"],
            answer: "yeast",
            audioURL: "https://well-lit-maintainer.com/audio_W7Ia4IbJ.mp3",
        },
        {
            id: "d46e3fc3-34f9-4ccc-9c57-4dd372bfa01a",
            part: 3,
            type: "Listening",
            question: "Terga comes virgo desparatus temptatio cicuta cohibeo.",
            options: ["expansion", "plugin", "railway", "season"],
            answer: "season",
            audioURL: "https://sugary-apparatus.info/audio_G0qRUr64.mp3",
        },
        {
            id: "a9d88239-61a2-4661-bc9c-b5f1ffc3bfef",
            part: 3,
            type: "Listening",
            question: "Corroboro volva cogito curiositas coruscus.",
            options: ["tinderbox", "heartbeat", "thongs", "yin"],
            answer: "thongs",
            audioURL: "https://unfit-intent.org/audio_GbIHVFGW.mp3",
        },
        {
            id: "cb8fc98b-927a-4b86-ad2a-b0f60947fba0",
            part: 3,
            type: "Listening",
            question:
                "Tergum succurro volo certe conatus nisi dicta comptus admiratio velut aedificium calculus denego cariosus vinculum.",
            options: ["pilot", "embarrassment", "skean", "nerve"],
            answer: "pilot",
            audioURL: "https://rowdy-pantyhose.net/audio_6UsJu86i.mp3",
        },
        {
            id: "6c1fad36-1e43-4831-8807-7a0714cc84f1",
            part: 3,
            type: "Listening",
            question:
                "Valeo turba aperio cupiditas consequuntur denique adinventitias blandior thema ventus sui tabesco est tactus.",
            options: ["taxicab", "perp", "developmental", "tackle"],
            answer: "developmental",
            audioURL: "https://smart-leading.org/audio_34BKFOQX.mp3",
        },
        {
            id: "49738c26-fef5-4ea5-a6e7-756a0ea7ba9f",
            part: 3,
            type: "Listening",
            question: "Defleo bardus alius vestigium sub temporibus.",
            options: ["lace", "adult", "alliance", "cycle"],
            answer: "alliance",
            audioURL: "https://scornful-litter.name/audio_En1Djxh5.mp3",
        },
        {
            id: "7bc1da75-4daf-48bf-aaf4-a9024d8a6da3",
            part: 3,
            type: "Listening",
            question: "Calamitas excepturi carus crur absens despecto acidus.",
            options: ["onset", "equal", "postbox", "publicity"],
            answer: "publicity",
            audioURL: "https://reasonable-loyalty.name/audio_1nIfjAsX.mp3",
        },
        {
            id: "a4fd64fd-8b1b-4253-87b3-004f6c6cb4eb",
            part: 3,
            type: "Listening",
            question:
                "Attollo maiores collum color adsuesco custodia auctor vesco deficio incidunt quasi.",
            options: ["fit", "consistency", "deployment", "cinema"],
            answer: "consistency",
            audioURL: "https://unruly-bidet.info/audio_VkxRNZoU.mp3",
        },
        {
            id: "f12f2c46-2f3d-4057-8cf7-62893a5e0474",
            part: 3,
            type: "Listening",
            question:
                "Cedo aedificium cubo sto solio molestias absorbeo territo cohibeo decipio cohors brevis.",
            options: ["declaration", "humidity", "bandwidth", "instructor"],
            answer: "declaration",
            audioURL: "https://earnest-embarrassment.org/audio_4IFN4G0N.mp3",
        },
        {
            id: "81eb83e1-a2a0-4887-b3b8-bfade2df3d5e",
            part: 3,
            type: "Listening",
            question: "Vicinus conor corporis vulpes volutabrum.",
            options: ["seal", "backbone", "cellar", "disk"],
            answer: "seal",
            audioURL: "https://serpentine-council.name/audio_t7xMB9K1.mp3",
        },
        {
            id: "5ca689ab-ca82-4c8c-8916-7befddbe5722",
            part: 3,
            type: "Listening",
            question:
                "Supra tabula degusto accusamus summopere advoco vita adeptio amet usque uxor sollicito.",
            options: ["sunbeam", "gradient", "loyalty", "term"],
            answer: "sunbeam",
            audioURL: "https://muffled-hunt.org/audio_9noOrWL6.mp3",
        },
        {
            id: "2fadc53d-6ffc-46d4-ad3a-09333cd12a86",
            part: 3,
            type: "Listening",
            question:
                "Aggredior cribro corporis solutio curso vero cuius adeo sit pax viscus.",
            options: ["dress", "papa", "heroine", "spirit"],
            answer: "spirit",
            audioURL: "https://important-stump.name/audio_8aoLvUhn.mp3",
        },
        {
            id: "1730f312-e14c-4403-bc19-2d92374d1987",
            part: 3,
            type: "Listening",
            question:
                "Appono addo conscendo adaugeo vergo corroboro coniuratio id synagoga amaritudo exercitationem.",
            options: ["mortise", "rationale", "elevation", "digestive"],
            answer: "elevation",
            audioURL: "https://willing-patroller.name/audio_lwiiFilX.mp3",
        },
        {
            id: "aba84140-f255-430d-b86a-02b7a12b0f6f",
            part: 3,
            type: "Listening",
            question:
                "Impedit degusto viduo clamo crustulum adeo blanditiis agnitio consuasor aliquam.",
            options: ["sanity", "igloo", "skyscraper", "postbox"],
            answer: "igloo",
            audioURL: "https://glass-outset.com/audio_giNX3Ydg.mp3",
        },
        {
            id: "204a0df0-3b28-452f-9667-dafcd7cc2f27",
            part: 3,
            type: "Listening",
            question:
                "Angelus cado socius supplanto tempora quod vulariter tracto.",
            options: ["precedent", "backburn", "tomatillo", "reach"],
            answer: "precedent",
            audioURL: "https://affectionate-wheel.com/audio_PfC1rxJL.mp3",
        },
        {
            id: "bc362df1-397c-40d1-98c3-10af4f25c590",
            part: 3,
            type: "Listening",
            question:
                "Caritas aro utrimque modi absens aestivus ater thema creber aggredior armarium tabernus.",
            options: ["compromise", "diagram", "cricket", "premise"],
            answer: "premise",
            audioURL: "https://discrete-allegation.biz/audio_2xJVo1a9.mp3",
        },
        {
            id: "7f279d6b-4f32-4c8d-a1bd-cc850407d482",
            part: 3,
            type: "Listening",
            question: "Vigilo decor venia bestia usitas.",
            options: ["simple", "jacket", "deed", "behest"],
            answer: "jacket",
            audioURL: "https://unhappy-seagull.info/audio_t6seeuZH.mp3",
        },
        {
            id: "f6129a69-b8d9-4417-8d9f-ada4c43d7b25",
            part: 3,
            type: "Listening",
            question:
                "Sumptus verus adinventitias solutio verumtamen auctor unus conservo ex abscido stips.",
            options: ["cook", "clavicle", "blossom", "affiliate"],
            answer: "cook",
            audioURL: "https://untimely-hammock.biz/audio_k7PD8tcK.mp3",
        },
        {
            id: "b0046e34-db6e-4bc6-b13d-7204074d9a98",
            part: 3,
            type: "Listening",
            question: "Vinum ciminatio cicuta pauper talis vos caries.",
            options: ["newsprint", "council", "lobster", "waterspout"],
            answer: "waterspout",
            audioURL: "https://warped-bracelet.org/audio_ZxzH3fPi.mp3",
        },
        {
            id: "a4829f96-1cf5-4dc2-a35d-83d61180e372",
            part: 3,
            type: "Listening",
            question: "Usus tardus candidus desino talus aegre vobis.",
            options: ["barracks", "cauliflower", "tinderbox", "design"],
            answer: "tinderbox",
            audioURL: "https://profuse-coin.com/audio_7uhBdLjI.mp3",
        },
        {
            id: "6fc389ba-8d03-4944-b5d4-572edbe668f3",
            part: 3,
            type: "Listening",
            question:
                "Decretum tamisium voluptatum repellendus demergo urbanus numquam.",
            options: ["aftermath", "marksman", "space", "wear"],
            answer: "marksman",
            audioURL: "https://naughty-spring.info/audio_FoFxN2ru.mp3",
        },
        {
            id: "efa5025e-9b3e-4bf0-bb7a-58d2ec276366",
            part: 3,
            type: "Listening",
            question:
                "Cilicium corona magnam quae triduana defungo contabesco inventore approbo.",
            options: ["pillow", "blowgun", "range", "typewriter"],
            answer: "range",
            audioURL: "https://hard-to-find-shipper.com/audio_7ujIPrCx.mp3",
        },
        {
            id: "2e0f86f6-fae3-472e-b1ff-37385a8b59b2",
            part: 3,
            type: "Listening",
            question: "Tum numquam vomer aptus benigne.",
            options: ["barge", "summary", "ostrich", "doing"],
            answer: "ostrich",
            audioURL: "https://french-thread.name/audio_xRKDAaKS.mp3",
        },
        {
            id: "ce8c2208-5d8a-4691-b13e-e32c792d83a8",
            part: 3,
            type: "Listening",
            question:
                "Debeo peccatus suffoco aqua taedium vinco infit concedo stips cenaculum capio dignissimos.",
            options: ["divine", "iridescence", "armoire", "mousse"],
            answer: "armoire",
            audioURL: "https://lone-lobster.info/audio_WL8opkQz.mp3",
        },
        {
            id: "901641be-9ed8-4296-99b0-e53a408ebff9",
            part: 3,
            type: "Listening",
            question:
                "Aqua odio aggero termes neque tenax confugo vapulus uberrime ara.",
            options: ["resource", "compromise", "pigsty", "vista"],
            answer: "pigsty",
            audioURL: "https://fussy-sweatshop.com/audio_zWjhCMED.mp3",
        },
    ],
};
